version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install      
  build:
    commands:
      - npm test
      - npm publish $PUBLISH_ARGS --unsafe-perm 